# docker build -t ap2 .
#
# docker run --privileged -h ap2 --rm -it -v ${PWD}:/host --user $(id -u) -w /home/dev ap2 bash

# docker run --name ap2-simmessa -d ap2-simmessa sleep 5m; docker cp ap2-simmessa:/home/dev/annepro2_c15_simmessa.bin .

FROM debian:bullseye
MAINTAINER Simone Messaggi <simmessa@gmail.com>

# put C15 or C18 here...
ENV MODEL=C15
ENV MODEL_LOW=c15

RUN sed -i \
    -e "s|deb.debian.org|debian.fastweb.it|g" \
    /etc/apt/sources.list

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential less git sudo \
  pkg-config libusb-1.0-0-dev gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib \
  ca-certificates

RUN adduser --disabled-password --gecos '' dev && \
    adduser dev sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN cd /home/dev; sudo -H -u dev git clone https://github.com/simmessa/qmk_firmware.git annepro-qmk --recursive --depth 1 
RUN cd /home/dev/annepro-qmk; sudo -H -u dev git pull 
RUN rm /home/dev/annepro-qmk/keyboards/annepro2/config.h
RUN cd /home/dev/annepro-qmk && make -Wno-error annepro2/${MODEL_LOW}:simmessa
# RUN cd /home/dev; sudo -H -u dev git clone https://github.com/simmessa/AnnePro2-Shine.git --recursive --depth 1 && cd AnnePro2-Shine && make MODEL=${MODEL}

RUN ls /home/dev/annepro-qmk/.build/*
RUN cp /home/dev/annepro-qmk/.build/annepro2_${MODEL_LOW}_simmessa.bin /home/dev/
#RUN cp /home/dev/AnnePro2-Shine/build/annepro2-shine-${MODEL}.bin /home/dev/

ENV TZ /usr/share/zoneinfo/Europe/Rome
