# docker build -t ap2 .
#
# docker run --privileged -h ap2 --rm -it -v ${PWD}:/host --user $(id -u) -w /home/dev ap2 bash

# docker run --name ap2-simmessa -d ap2-simmessa sleep 5m; docker cp ap2-simmessa:/home/dev/annepro2_c15_simmessa.bin .

# based on work made available by Davide Viti <zinosat@gmail.com>

FROM debian:bullseye
MAINTAINER Simone Messaggi <simmessa@gmail.com>

# The following might help if you live in Italy, otherwise you can choose a mirror in your country, please find a complete list on https://www.debian.org/mirror/
# country code is the 2 letters XX in ftp.XX.debian.org, uncomment the relevant line or feel free to alter this variable

# ENV DEBIAN_MIRROR=ftp.de.debian.org
# ENV DEBIAN_MIRROR=ftp.fr.debian.org
# ENV DEBIAN_MIRROR=ftp.es.debian.org
# ENV DEBIAN_MIRROR=ftp.uk.debian.org
# ENV DEBIAN_MIRROR=ftp.us.debian.org
ENV DEBIAN_MIRROR=ftp.it.debian.org

# Good for Italy, you might want to change this...
ENV TZ /usr/share/zoneinfo/Europe/Rome

# Set a close mirror for apt get
RUN sed -i \
    -e "s|deb.debian.org|${DEBIAN_MIRROR}|g" \
    /etc/apt/sources.list

  # pkg-config libusb-1.0-0-dev gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib \

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \
  build-essential less git sudo \
  pkg-config gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib \
  ca-certificates

# dummy sudo-enabled user for gcc make
RUN adduser --disabled-password --gecos '' dev && \
    adduser dev sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


ENV QMK_REPOSITORY=https://github.com/simmessa/qmk_firmware.git

#1st time clone
RUN cd /home/dev; sudo -H -u dev git clone ${QMK_REPOSITORY} annepro-qmk --recursive --depth 1

WORKDIR /home/dev
COPY entry-qmk.bash /home/dev/entry-qmk.bash
